# Use Node.js image as a base image
FROM node:18-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app will run on
EXPOSE 4000

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "run", "start:prod"]
