import { DataSource, DataSourceOptions } from 'typeorm';
import { Usertable } from './entitys/usertable';
import { Test } from './entitys/test';
import { PatPatientsInformation } from './entitys/pat_patients_information';
import { Patientsrx } from './entitys/patientsrx';
import { Rxmedicine } from './entitys/rxmedicine';
import { Rxexaminations } from './entitys/rxexaminations';

export const AppDataSource:DataSourceOptions = {
  type: 'mysql',
  host: '192.168.0.89',
  port: 3306,
  username: 'qmsdrmakbul',         // Update with your MySQL username
  password: 'Qmsdrmakbul24#',     // Update with your MySQL password
  database: 'qmsdrmakbul_db',  // Update with your MySQL database name
  entities: [Usertable, Test, PatPatientsInformation, Patientsrx, Rxmedicine, Rxexaminations],         // Add your entities here
  synchronize: true,        // Set to false in production
  logging: true,
};


  const dataSource = new DataSource(AppDataSource);
  export default dataSource;

  // "migration:generate": "npm run build && npm run typeorm -- migration:generate -d ./dist/data-source.js src/migrations/AutoGeneratedMigration",
// npm run typeorm -- migration:generate -d ./dist/data-source.js ./src/migrations/CreateEmployeeAndDepartmentTables
// npm run typeorm -- migration:generate -d ./dist/data-source.js ./src/migrations/CreateEmployeeAndDepartmentTables
// npm run typeorm -- migration:run -d ./data-source.ts
// npm run migration:generate
// npm run migration:run
